spring:
  profiles:
    active: e2e
  jackson:
    deserialization:
      ACCEPT_FLOAT_AS_INT: false

---
spring:
  config:
    activate:
      on-profile: prod
erp:
  url: https://dummyjson.com

---
spring:
  config:
    activate:
      on-profile: qa
erp:
  url: https://dummyjson.com

---
spring:
  config:
    activate:
      on-profile: e2e
erp:
  url: https://dummyjson.com

---
spring:
  config:
    activate:
      on-profile: acc

erp:
  url: http://localhost:8089