test:
  eshop:
    ui:
      baseUrl: http://localhost:3004
    api:
      baseUrl: http://localhost:8084
  erp:
    api:
      baseUrl: http://localhost:9004/erp
  tax:
    api:
      baseUrl: http://localhost:9004/tax

