test:
  eshop:
    ui:
      baseUrl: http://localhost:3002
    api:
      baseUrl: http://localhost:8082
  erp:
    api:
      baseUrl: http://localhost:9002/erp
  tax:
    api:
      baseUrl: http://localhost:9002/tax

