spring:
  profiles:
    active: e2e
  jackson:
    deserialization:
      ACCEPT_FLOAT_AS_INT: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5401/eshop}
    username: ${SPRING_DATASOURCE_USERNAME:eshop_user}
    password: ${SPRING_DATASOURCE_PASSWORD:eshop_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:3001}

error:
  types:
    base-url: ${ERROR_TYPES_BASE_URL:https://api.optivem.com/errors}
    validation-error: ${error.types.base-url}/validation-error
    resource-not-found: ${error.types.base-url}/resource-not-found
    bad-request: ${error.types.base-url}/bad-request
    internal-server-error: ${error.types.base-url}/internal-server-error

---
spring:
  config:
    activate:
      on-profile: e2e
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
erp:
  url: http://external:9001/erp/api
tax:
  url: http://external:9001/tax/api

---
spring:
  config:
    activate:
      on-profile: qa
erp:
  url: http://external:9001/erp/api
tax:
  url: http://external:9001/tax/api

---
spring:
  config:
    activate:
      on-profile: prod
erp:
  url: http://erp-api:3000
tax:
  url: http://tax-api:3000
